'use client';

import { DownloadIcon } from 'lucide-react';
import { Button } from '../ui/button';

interface DownloadSummaryButtonProps {
  title: string;
  summaryText: string;
  fileName: string;
  createdAt: string;
}
const DownloadSummaryButton = ({
  title,
  summaryText,
  fileName,
  createdAt,
}: DownloadSummaryButtonProps) => {
  const handleDownload = () => {
    try {
      const summaryContent = `# ${title} 
Generated Summary 
Generated on: ${new Date(createdAt).toLocaleDateString()}

${summaryText}



Original File: ${fileName}
Generated by Sommaire 
`;

      const blob = new Blob([summaryContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);

      const link = document.createElement('a');
      link.href = url;
      link.download = `Summary-${title.replace(/[^a-zA-Z0-9]/gi, '_')}_summary.txt`;

      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error downloading summary:', error);
    }
  };

  return (
    <div>
      <Button
        size='sm'
        onClick={handleDownload}
        className='h-8 px-3 text-rose-600 hover:text-rose-700 bg-rose-100 hover:bg-rose-50 cursor-pointer'
      >
        <DownloadIcon className='h-4 w-4 mr-1' />
        Download Summary
      </Button>
    </div>
  );
};

export default DownloadSummaryButton;
